CREATE TABLE
  ORDER_ITEMS (
    ORDER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL
  );

CREATE TABLE
  ORDER_DETAILS (
    ORDER_DETAIL_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    QUANTITY TINYINT NOT NULL,
    ORDER_PRICE SMALLINT NOT NULL,
    DISCOUNT_RATE TINYINT NOT NULL DEFAULT 0
  );